import { vi } from 'vitest';

// Global mocks for all tests - prevent real connections
vi.mock('@erp/database', () => ({
  prisma: {
    $queryRaw: vi.fn().mockResolvedValue([]),
    $connect: vi.fn(),
    $disconnect: vi.fn(),
    tenant: { findUnique: vi.fn(), findMany: vi.fn(), count: vi.fn(), create: vi.fn(), update: vi.fn(), updateMany: vi.fn() },
    tenantSettings: { findUnique: vi.fn(), update: vi.fn() },
    user: { findUnique: vi.fn(), findMany: vi.fn(), count: vi.fn(), create: vi.fn(), update: vi.fn(), updateMany: vi.fn(), createMany: vi.fn() },
    role: { findUnique: vi.fn(), findMany: vi.fn() },
    permission: { findUnique: vi.fn(), findMany: vi.fn(), upsert: vi.fn() },
    userRole: { findMany: vi.fn(), upsert: vi.fn(), deleteMany: vi.fn() },
    rolePermission: { upsert: vi.fn() },
    session: { findUnique: vi.fn(), findMany: vi.fn(), create: vi.fn(), update: vi.fn(), updateMany: vi.fn(), count: vi.fn() },
    auditLog: { findMany: vi.fn(), count: vi.fn(), create: vi.fn() },
    featureFlag: { findMany: vi.fn(), upsert: vi.fn() },
    institution: { findMany: vi.fn(), count: vi.fn() },
    student: { findUnique: vi.fn(), findMany: vi.fn(), findFirst: vi.fn(), count: vi.fn(), create: vi.fn(), createMany: vi.fn(), update: vi.fn(), updateMany: vi.fn(), groupBy: vi.fn().mockResolvedValue([]) },
    parent: { create: vi.fn() },
    parentStudent: { findMany: vi.fn(), upsert: vi.fn(), deleteMany: vi.fn() },
    studentDocument: { findMany: vi.fn(), create: vi.fn(), update: vi.fn() },
    certificate: { findMany: vi.fn(), create: vi.fn() },
    teacher: { findUnique: vi.fn(), findMany: vi.fn(), count: vi.fn(), create: vi.fn(), update: vi.fn() },
    teacherSubject: { findMany: vi.fn(), deleteMany: vi.fn(), createMany: vi.fn() },
    teacherQualification: { findMany: vi.fn(), create: vi.fn(), delete: vi.fn() },
    teacherExperience: { findMany: vi.fn(), create: vi.fn(), delete: vi.fn() },
    teacherSalary: { findUnique: vi.fn(), upsert: vi.fn() },
    teacherDocument: { findMany: vi.fn(), create: vi.fn(), update: vi.fn() },
    staff: { count: vi.fn() },
    attendance: { findMany: vi.fn(), count: vi.fn(), upsert: vi.fn(), groupBy: vi.fn().mockResolvedValue([]) },
    leave: { findMany: vi.fn(), groupBy: vi.fn().mockResolvedValue([]) },
    holiday: { findMany: vi.fn(), count: vi.fn() },
    timetable: { findMany: vi.fn() },
    academicSession: { findMany: vi.fn(), findUnique: vi.fn(), create: vi.fn(), update: vi.fn(), updateMany: vi.fn() },
    department: { findMany: vi.fn(), findUnique: vi.fn(), create: vi.fn(), update: vi.fn() },
    course: { findMany: vi.fn(), findUnique: vi.fn(), create: vi.fn(), update: vi.fn() },
    class: { findMany: vi.fn(), findUnique: vi.fn(), create: vi.fn(), update: vi.fn() },
    section: { findMany: vi.fn(), findUnique: vi.fn(), create: vi.fn(), update: vi.fn() },
    subject: { findMany: vi.fn(), findUnique: vi.fn(), create: vi.fn(), update: vi.fn() },
    subjectGroup: { findMany: vi.fn(), create: vi.fn(), delete: vi.fn() },
    classTeacherAssignment: { findFirst: vi.fn(), findMany: vi.fn(), upsert: vi.fn(), delete: vi.fn() },
    subjectTeacherAssignment: { findFirst: vi.fn(), findMany: vi.fn(), upsert: vi.fn(), delete: vi.fn() },
    promotionRule: { findMany: vi.fn(), create: vi.fn(), update: vi.fn(), delete: vi.fn() },
    calendarEvent: { findMany: vi.fn(), create: vi.fn(), update: vi.fn() },
    feeCategory: { findMany: vi.fn(), create: vi.fn(), update: vi.fn() },
    feeStructure: { findMany: vi.fn(), findUnique: vi.fn(), create: vi.fn(), update: vi.fn() },
    invoice: { findMany: vi.fn(), findUnique: vi.fn(), count: vi.fn(), create: vi.fn(), update: vi.fn(), aggregate: vi.fn().mockResolvedValue({ _sum: { totalAmount: 0, paidAmount: 0, outstandingAmount: 0 }, _count: { id: 0 } }) },
    payment: { findMany: vi.fn(), findUnique: vi.fn(), count: vi.fn(), create: vi.fn(), update: vi.fn(), aggregate: vi.fn().mockResolvedValue({ _sum: { amount: 0 }, _count: { id: 0 } }), groupBy: vi.fn().mockResolvedValue([]) },
    discount: { findMany: vi.fn(), create: vi.fn() },
    scholarship: { findMany: vi.fn(), create: vi.fn() },
    exam: { findMany: vi.fn(), findUnique: vi.fn(), count: vi.fn(), create: vi.fn(), update: vi.fn() },
    questionBank: { findMany: vi.fn() },
    grade: { findMany: vi.fn(), findFirst: vi.fn(), create: vi.fn(), update: vi.fn(), delete: vi.fn() },
    result: { findMany: vi.fn(), upsert: vi.fn(), updateMany: vi.fn() },
    homework: { findMany: vi.fn(), findUnique: vi.fn(), count: vi.fn(), create: vi.fn(), update: vi.fn() },
    homeworkAttachment: { create: vi.fn() },
    submission: { findUnique: vi.fn(), findMany: vi.fn(), create: vi.fn(), update: vi.fn() },
    studyMaterial: { findMany: vi.fn(), findUnique: vi.fn(), count: vi.fn(), create: vi.fn(), update: vi.fn() },
    book: { findMany: vi.fn(), findUnique: vi.fn(), findFirst: vi.fn(), count: vi.fn(), create: vi.fn(), update: vi.fn(), aggregate: vi.fn().mockResolvedValue({ _sum: { totalCopies: 100, availableCopies: 80 } }), groupBy: vi.fn().mockResolvedValue([]) },
    bookIssue: { findMany: vi.fn(), findUnique: vi.fn(), count: vi.fn(), create: vi.fn(), update: vi.fn(), groupBy: vi.fn().mockResolvedValue([]) },
    notificationTemplate: { findMany: vi.fn(), findFirst: vi.fn(), create: vi.fn(), update: vi.fn(), delete: vi.fn() },
    notification: { findMany: vi.fn(), findUnique: vi.fn(), count: vi.fn(), create: vi.fn(), createMany: vi.fn(), update: vi.fn(), updateMany: vi.fn(), groupBy: vi.fn().mockResolvedValue([]) },
    websitePage: { findMany: vi.fn(), findUnique: vi.fn(), create: vi.fn(), update: vi.fn() },
    blogPost: { findMany: vi.fn(), findUnique: vi.fn(), count: vi.fn(), create: vi.fn(), update: vi.fn() },
    galleryItem: { findMany: vi.fn(), create: vi.fn(), delete: vi.fn() },
    contactEnquiry: { findMany: vi.fn(), create: vi.fn(), update: vi.fn() },
    plan: { findMany: vi.fn(), findUnique: vi.fn(), create: vi.fn() },
    subscription: { findFirst: vi.fn(), findMany: vi.fn(), create: vi.fn(), update: vi.fn() },
    organizationConfig: { findMany: vi.fn(), upsert: vi.fn(), deleteMany: vi.fn() },
  },
}));

vi.mock('../../config/index.js', () => ({
  env: {
    jwtAccessSecret: 'test-secret',
    jwtRefreshSecret: 'test-refresh-secret',
    jwtAccessExpiry: '15m',
    jwtRefreshExpiry: '7d',
    nodeEnv: 'test',
    apiPrefix: '/api/v1',
    corsOrigins: ['http://localhost:3000'],
    rateLimitWindowMs: 900000,
    rateLimitMaxRequests: 1000,
    logLevel: 'silent',
    logFormat: 'json',
    appName: 'test',
    isDevelopment: () => false,
    isProduction: () => false,
    isTest: () => true,
  },
  logger: { info: vi.fn(), warn: vi.fn(), error: vi.fn(), fatal: vi.fn(), debug: vi.fn() },
  redis: { get: vi.fn().mockResolvedValue(null), setex: vi.fn().mockResolvedValue('OK'), del: vi.fn().mockResolvedValue(1), incr: vi.fn().mockResolvedValue(1), expire: vi.fn().mockResolvedValue(1), lpush: vi.fn().mockResolvedValue(1), ltrim: vi.fn().mockResolvedValue('OK'), lrange: vi.fn().mockResolvedValue([]), ping: vi.fn().mockResolvedValue('PONG'), connect: vi.fn() },
  connectRedis: vi.fn(),
  disconnectRedis: vi.fn(),
  notificationQueue: { add: vi.fn().mockResolvedValue({}) },
  emitToUser: vi.fn(),
  emitToTenant: vi.fn(),
}));
